image: python:3.9

pipelines:
  default:
    - step:
        name: Build & Test Backend
        caches:
          - python
        script:
          - cd backend
          - pip install -r requirements.txt
          - python manage.py test

    - step:
        name: Build & Test Frontend
        image: node:14
        caches:
          - node
        script:
          - cd frontend
          - npm install
          - npm run test

definitions:
  caches:
    python: ~/.cache/pip
    node: ~/.npm
