[tool.black]
line-length = 120
target-version = ['py310']
extend-exclude = '''
    .mypy_cache
    | .pytest_cache,
    | .ruff_cache
    | __pypackages__
    | .venv
    | migrations
    | manage.py
'''
color = true
