# Generated by Django 5.1.2 on 2024-10-11 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="status",
            field=models.CharField(
                choices=[("P", "Pending"), ("IP", "In Progress"), ("D", "Done")],
                default="P",
                max_length=31,
            ),
        ),
    ]
