# Generated by Django 5.1.2 on 2024-10-11 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="date_joined",
            new_name="joined_at",
        ),
    ]
