name: Frontend CI Pipeline

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and export
      uses: docker/build-push-action@v6
      with:
        tags: ${{ github.repository_owner }}/frontend:latest
        outputs: type=docker,dest=/tmp/frontend-image.tar
        file: frontend/Dockerfile
    
    - name: Upload as an artifact
      uses: actions/upload-artifact@v4
      with:
        name: frontend-image
        path: /tmp/frontend-image.tar

  lint-format:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Download as an artifact
      uses: actions/download-artifact@v4
      with:
        name: frontend-image
        path: /tmp
        
    - name: Load image
      run: |
        docker load --input /tmp/frontend-image.tar
        docker image ls -a
        npm list -g --depth=0

    - name: Lint and format
      run: |
        docker run --rm -v ${{ github.workspace }}:/app -w /app/frontend ${{ github.repository_owner }}/frontend:latest npm run lint

      # cd frontend
      # npm run lint

  test:
    runs-on: ubuntu-latest
    needs: lint-format
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Run frontend tests
      run: |
        docker run --rm -v ${{ github.workspace }}:/app -w /app/frontend ${{ github.repository_owner }}/frontend:latest npm test
      # cd frontend
      # npm test
