name: Frontend CI Pipeline

on:
  pull_request:
    branches:
      - master
      - release/*
  push:
    branches:
      - master
      - release/*
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and export
        uses: docker/build-push-action@v6
        with:
          tags: ${{ github.repository_owner }}/frontend:latest
          outputs: type=docker,dest=/tmp/frontend-image.tar
          file: frontend/Dockerfile
      
      - name: Upload as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-image
          path: /tmp/frontend-image.tar

  lint-format:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download as an artifact
        uses: actions/download-artifact@v4
        with:
          name: myimage
          path: /tmp
          
      - name: Load image
        run: |
          docker load --input /tmp/myimage.tar
          docker image ls -a

      -name: Lint and format
        run: |
          cd frontend
          npm run lint
        continue-on-error: true

  test:
    runs-on: ubuntu-latest
    needs: lint-format
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run frontend tests
        run: |
          cd frontend
          npm test
        continue-on-error: true