on:
  push:
    branches:
      - master
      - release/*
  workflow_dispatch:

jobs:
  backend:
    uses: ./.github/workflows/backend-ci.yml

  frontend:
    uses: ./.github/workflows/backend-ci.yml

  publish:
    runs-on: ubuntu-latest
    needs: [backend, frontend]
