name: Publish

on:
  push:
    branches:
      - master
      - dev
  workflow_dispatch:

jobs:
  backend:
    uses: ./.github/workflows/backend-ci.yml

  frontend:
    uses: ./.github/workflows/backend-ci.yml

  publish:
    runs-on: ubuntu-latest
    needs: [backend, frontend]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download as an artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-image
          path: /tmp

      - name: Load image
        run: |
          docker load --input /tmp/backend-image.tar

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v3
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/mipt-6sem-inprac:latest
